send_meter_reading:
  fields:
    entry_id:
      required: true
      selector:
        config_entry:
          integration: energy_tracker
    device_id:
      required: true
      example: "deadbeef-dead-beef-dead-beefdeadbeef"
      selector:
        text:
          type: text
    source_entity_id:
      required: true
      selector:
        entity:
          domain:
            - sensor
            - input_number
            - number
    allow_rounding:
      required: false
      default: true
      selector:
        boolean:
